package stocktrader;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;

public class MotionMapper {

	public static void main(String[] args) throws Exception {
		String[] tickers = { "FLWS", "FCTY", "FCCY", "SRCE", "TCHC", "VNET",
				"SSRX", "JOBS", "EGHT", "AVHI", "SHLM", "AONE", "AAON", "ASTM",
				"ABAX", "ABMD", "AXAS", "ACTG", "ACHC", "ACAD", "ACCL", "ANCX",
				"ARAY", "ACRX", "ACET", "ACHN", "ACIW", "APKT", "ACNB", "ACOR",
				"ACFN", "ACTS", "ACPW", "ATVI", "BIRT", "ACUR", "ACXM", "ADES",
				"ADUS", "AEY", "ADEP", "ADBE", "ADTN", "AEIS", "ADVS", "AVCA",
				"AEGR", "AEGN", "AEHR", "AEPI", "AVAV", "AEZS", "ATRM", "AFCE",
				"AFFY", "AFFX", "AGEN", "AGYS", "AIRM", "AIRT", "ATSG", "AMCN",
				"AIXG", "AKAM", "AKRX", "ALSK", "AMRI", "ALXN", "ALXA", "ALCO",
				"ALGN", "ALIM", "ALKS", "ALGT", "ALLB", "ABVA", "AFOP", "ALNC",
				"AHGP", "ARLP", "AHPI", "AMOT", "ALTH", "ALLT", "MDRX", "AFAM",
				"ALNY", "AOSL", "ATEC", "ALTI", "ALTR", "ALTE", "ASPS", "APSA",
				"AIMC", "ALVR", "AMAG", "AMRN", "AMZN", "EPAX", "AMBT", "AMCX",
				"AMED", "UHAL", "ASBI", "ATAX", "AMOV", "AGNC", "AGNCP",
				"MTGE", "ACAS", "ANCI", "AETI", "AMIC", "ALRN", "AMNB", "ANAT",
				"APFC", "APEI", "ARII", "ARCP", "ARCT", "AMRB",
				"ASEI", "AMSWA", "AMSC", "AMWD", "CRMT", "ARGN", "ABCB",
				"AMSF", "ASRV", "ASRVP", "ASCA", "ATLO", "AMGN", "FOLD",
				"AMKR", "AMPL", "AMPE", "AMSG", "ASYS", "AFSI", "AMLN", "AMRS",
				"ANAC", "ANAD", "ADI", "ALOG", "ANLY", "ANEN",
				"ACOM", "ANCB", "AMCF", "ANDA", "ANDAU", "ANDAW",
				"ANGN", "ANGI", "ANGO", "ANIK", "ANNB", "ANSS", "ANTH",
				"APAGF", "ATNY", "APOG", "APOL", "AINV", "AAPL", "ARCI",
				"AMAT", "AMCC", "AREX", "APRI", "ARCW", "ABIO", "ACGL", "ACAT",
				"RDEA", "ARDNA", "ARNA", "ARCC", "AGII", "ARIA", "ARBA",
				"ARKR", "ABFS", "ARMH", "ARTX", "ARQL", "ARRY", "ARRS", "AROW",
				"ARWR", "ARTNA", "ARTC", "ARTW", "ARUN", "ASBB", "ASNA",
				"ASCMA", "ASTI", "AERL", "APWC", "ASIA", "ASMI", "ASML",
				"AZPN", "APPY", "AACC", "ASBC", "ASBCW", "ASFI", "ATEA",
				"ASTE", "ASTX", "ALOT", "ATRO", "ASTC", "ASUR", "ATAI", "ATHN",
				"AFCB", "ATHX", "AAME", "ACFC", "ATNI", "AAWW", "ATML", "ATMI",
				"ATPG", "ATRC", "ATRI", "AUBN", "ADNC", "AUDC", "AAC", "AACOU",
				"AACOW", "AUTH", "ADAT", "ABTL", "ADSK", "ADP", "AMAP", "AUXL",
				"AVGO", "AVNR", "AVEO", "AVII", "AVNW", "AVID", "CAR", "AWRE",
				"ACLS", "AXTI", "BCOM", "BOSC", "BIDU", "BCPC", "BWINA",
				"BWINB", "BLDP", "BANF", "BANFP", "BTFG", "BKMU", "BOCH",
				"BMRC", "BKSC", "BOTJ", "OZRK", "BOVA", "BBXT", "BFIN", "BANR",
				"BBSI", "BSET", "BV", "BBCN", "BCBP", "BCDS", "BCSB", "BEAV",
				"BFED", "BECN", "BBGI", "BEBE", "BBBY", "BELFA", "BELFB",
				"BNCL", "BNHN", "BERK", "BHLB", "BGMD", "BGCP", "BGSC",
				"BGSCU", "BGSCW", "BIDZ", "BGFV", "BASI", "BIOC", "BCRX",
				"BIOD", "BDSI", "BIOF", "BIIB", "BIOL", "BLRX", "BMRN", "BMTI",
				"BRLI", "BPAX", "BIOS", "BSTC", "BSPM", "BDMS", "BJRI", "BBOX",
				"BDE", "BLKB", "BKCC", "ADRA", "ADRD", "ADRE", "ADRU", "BCOR",
				"NILE", "MNGL", "MNGLU", "MNGLW", "BFLY", "BKEP", "BKEPP",
				"BPHX", "BMC", "BNCN", "BOBE", "BODY", "BOFI", "WIFI", "BOKF",
				"BOLT", "BONA", "BNSO", "BAMM", "BPFH", "BPFHW", "EPAY",
				"BBRG", "BBEP", "BDGE", "BBNK", "BLIN", "BRID",
				"BCOV", "CELL", "BKBK", "BRCM", "BSFT", "BVSN", "BYFC", "BWEN",
				"BRCD", "BRKL", "BRKS", "BRKR", "BMTC", "BLMT", "BSDM", "BSQR",
				"BTUI", "BWLD", "BLDR", "BUR", "CFFI", "CHRW", "CA", "CCMP",
				"CACH", "CDNS", "CADX", "CDZI", "CZR", "CSTE", "PRSS", "CLMS",
				"CAMP", "CVGW", "CFNB", "CALD", "CALM", "CLMT", "ABCD", "CAFI",
				"CAC", "CAMT", "CSIQ", "CPHC", "CBNJ", "CPLA", "CBKN", "CCBG",
				"CPLP", "CSWC", "CFFN", "CPST", "CARB", "CRDC", "CFNL", "CRME",
				"BEAT", "CSII", "CATM", "CECO", "CBOU", "CKEC", "CLBH", "CART",
				"CRZO", "CRRB", "TAST", "CARV", "CASM", "CACB", "CSCD", "CWST",
				"CASY", "CASS", "CMRG", "CHSI", "CPRX", "CATY", "CVCO", "CAVM",
				"CAZA", "CAZAU", "CAZAW", "CBEY", "CBOE", "CDII", "CFK",
				"CECE", "CELG", "CELGZ", "CTIC", "CLDX", "CLSN", "CEMP",
				"CNBC", "CSFL", "CEBK", "CEDC", "CETV", "CFBK", "CENT",
				"CENTA", "CVCY", "CENX", "CNBKA", "CNTY", "CPHD", "CRDN",
				"CRNT", "CERP", "CERE", "CERN", "CERS", "CEVA", "CITZ", "CHMP",
				"CYOU", "CTHR", "CHRM", "CHRS", "GTLS", "CHTR", "CHFN", "CHKP",
				"CHTP", "CEMI", "CHFC", "CCXI", "CHKE", "CHEV", "CBNK", "CADC",
				"CALI", "CAAS", "CBAK", "CBPO", "CCCL", "CCCLU", "CCCLW",
				"JRJC", "CHOP", "CGEI", "CGEIU", "CGEIW", "HGSH", "CHLN",
				"CNIT", "CJJD", "HTHT", "CHNR", "NKBP", "CPSL", "CREG", "CPGI",
				"CSUN", "CNTF", "CTDC", "CTFO", "CVVT", "CXDC", "CNYD", "CCIH",
				"CAST", "CEDU", "CNET", "CHDX", "IMOS", "CHSCP", "CHDN",
				"CHYR", "CIEN", "DFR", "CIMT", "CINF", "CIDM", "CTAS", "CRUS",
				"CSCO", "CTRN", "CZNC", "CZWI", "CZFC", "CIZN", "CRBC", "CSBC",
				"CTXS", "CHCO", "CTEL", "CWEI", "CDTI", "CLNE", "CLNT", "CLFD",
				"CLRO", "CLIR", "CLWR", "CBLI", "CKSW", "CSBK", "CLVS", "CME",
				"CMSB", "CCNE", "CISG", "COBZ", "COBR", "COKE", "CDXS", "CVLY",
				"JVA", "CCOI", "CGNX", "CTSH", "COGO", "COHR", "COHU", "CSTR",
				"CWTR", "CCIX", "CLCT", "COBK", "CBAN", "COLB", "CBRX", "COLM",
				"CMCO", "CBMX", "CBMXW", "CMCSA", "CMCSK", "CBSH", "CNAF",
				"CVGI", "CTCH", "JCS", "CBIN", "CFFC", "CPBC", "CTBI", "CWBC",
				"CVLT", "GNOM", "GSJK", "CCRT", "CGEN", "CPSI", "CTGX", "CPWR",
				"SCOR", "CHCI", "CMTL", "CMVT", "CPTS", "CNQR", "CCUR", "CNMD",
				"CTWS", "CONN", "CNSL", "CWCO", "CTCT", "CPSS", "CPNO", "CPRT",
				"CORT", "CORE", "COCO", "CSOD", "CRTX", "CNDO", "CRVL", "COSI",
				"CPWM", "CSGP", "COST", "CRRC", "CVTI", "COWN", "CRAI", "CBRL",
				"BREW", "CRAY", "CACC", "CRED", "CREE", "CRFN", "CRESW",
				"CRESY", "CXPO", "CROX", "ATX", "CCRN", "CRDS", "XTXI", "XTEX",
				"CRWS", "CRWN", "CRMB", "CRMBU", "CRMBW", "CRYP", "CSGS",
				"CSPI", "CSRE", "CTCM", "CTIB", "CTRP", "CBST", "CUI", "CPIX",
				"CMLS", "CRIS", "CUTR", "CVBF", "CVV", "CYAN", "CYBX", "CYBE",
				"CYBI", "CYCC", "CYCCP", "CYMI", "CYNO", "CY", "CYTK", "CYTX",
				"CYTXW", "CYTR", "DMED", "DAEG", "DJCO", "DAKT", "DARA",
				"DAIO", "DTLK", "DRAM", "DWCH", "DWSN", "DSTI", "TRAK", "DECK",
				"DEER", "DHRM", "DCTH", "DLIA", "DELL", "DGAS", "PROJ", "DNDN",
				"DENN", "XRAY", "DEPO", "DSCI", "DEST", "DSWL", "DXCM", "DLLR",
				"DIAL", "DLGC", "DMND", "DHFT", "DHIL", "DCIX", "DGII", "DMRC",
				"DRAD", "DGLY", "DCIN", "DGIT", "DRIV", "DCOM", "DIOD", "MKTS",
				"DTV", "DISCA", "DISCB", "DISCK", "DSCO", "DISH", "DITC",
				"DNBF", "DLTR", "DGICA", "DGICB", "DMLP", "DORM", "HILL",
				"DBLE", "DBLEP", "DOVR", "DRWI", "DWA", "DRYS", "DSPG", "DTSI",
				"DUCK", "DNKN", "DRRX", "DUSA", "DXPE", "DYAX", "DYII", "BOOM",
				"DRCO", "DYSL", "DYNT", "DVAX", "DVOX", "ETFC", "EBMT", "EGBN",
				"EGLE", "EROC", "ELNK", "EWBC", "EML", "EIHI", "EVBS", "ESIC",
				"EBAY", "EBIX", "ELON", "ECHO", "ECTE", "SATS", "EEI", "ECTY",
				"EDAC", "EDAP", "EF", "EDGR", "EDGW", "EDMC", "EDUC", "EVAC",
				"EFUT", "EGAN", "EHTH", "BAGL", "EMITF", "ESLT", "ESYS",
				"ELRC", "ESIO", "EA", "EFII", "ELSE", "RDEN", "ESBK", "LONG",
				"ELTK", "EMCI", "EMCF", "EMKR", "EMMS", "EMMSP", "NYNY",
				"EBTX", "ECPG", "WIRE", "ENDP", "ECYT", "ELGX", "ERII", "EXXI",
				"ENOC", "ENG", "ENPH", "ESGR", "ENTG", "ETRM", "EBTC", "EFSC",
				"ENMD", "ENTR", "ENVI", "ENZN", "EONC", "EPIQ", "PLUS", "EPHC",
				"EPOC", "EQIX", "ERT", "EAC", "ERIC", "ERIE",
				"ESBF", "ESCA", "ESMC", "ESSA", "ESSX", "CLWT", "EEFT", "ESEA",
				"EVEP", "EVOL", "EXAS", "EXAC", "EXAR", "EDS", "EXEL", "EXFO",
				"XIDE", "EXLS", "EXPE", "EXPD", "EXPO", "ESRX", "EXLP", "EXTR",
				"EZCH", "EZPW", "FFIV", "FB", "FRP", "FALC", "DAVE", "FARM",
				"FFKT", "FMNB", "FARO", "FAST", "FBSS", "FBRC", "FDML", "FFCO",
				"FEIC", "FHCO", "FFDF", "FSBI", "ONEQ", "LION", "FDUS", "FRGI",
				"FSC", "FITB", "FITBP", "FNGN", "FISI", "FNSR", "FABK", "FBNC",
				"FNLC", "BUSE", "FBIZ", "FCAL", "FCVA", "FCAP", "FCFS", "FCZA",
				"FCNCA", "FCLF", "FCBC", "FCCO", "FBNK", "FDEF", "FFBH",
				"FFNM", "FFBC", "FFBCW", "FFIN", "THFF", "FFCH", "FFNW",
				"FFKY", "FIBK", "FMFC", "FRME", "FMBI", "FNFG", "BANC",
				"BANCL", "FRCCO", "FSFG", "FSGI", "FSLR", "FSBK", "BICK", "CU",
				"PLTM", "CARZ", "SKYY", "QABA", "FONE", "GRID", "QCLN", "QQEW",
				"QQXT", "QTEC", "FUNC", "FBMI", "FCFC", "SVVC", "FMER", "FSRV",
				"FISV", "FSCI", "FLML", "FLXS", "FLEX", "FLIR", "FLOW", "FLDM",
				"FFIC", "FNBN", "FMCN", "FONR", "VIFL", "FES", "FORM", "FORTY",
				"FORR", "FTNT", "FWRD", "FORD", "FOSL", "FWLT", "FXCB", "FRAN",
				"FELE", "FRNK", "FRED", "FREE", "RAIL", "FEIM", "FFN", "FTR",
				"FFEX", "FSII", "FSYS", "FTEK", "FCEL", "FULL", "FULT", "FURX",
				"FSIN", "FFHL", "FXEN", "GKSR", "WILC", "GAIA", "GALT",
				"GALTU", "GALTW", "GALE", "GPIC", "GRMN", "GKNT", "GENC",
				"GNCMA", "GFN", "GFNCL", "GFNCZ", "GENE", "GNMK", "GHDX",
				"GPRO", "GNTX", "GENT", "GTIV", "GNVC", "GEOY", "GMET",
				"GMETP", "GEOI", "GABC", "GERN", "GEVO", "ROCK", "GIGM",
				"GIGA", "GIII", "GILT", "GILD", "GIVN", "GBCI", "GLAD",
				"GLADP", "GOOD", "GOODN", "GOODO", "GOODP", "GAIN", "GAINP",
				"GLCH", "GLBZ", "GLGL", "EAGL", "EAGLU", "EAGLW", "GBLI",
				"GLPW", "GSOL", "QQQM", "QQQV", "SOCL", "QQQC", "GSAT", "GAI",
				"GSM", "GCOM", "GLBS", "GLUU", "GLNG", "GMLP", "GLDC", "GOLF",
				"GBDC", "GTIM", "GOOG", "GMAN", "LOPE", "GCFB", "GRVY", "GRMH",
				"GLDD", "GSBC", "GRNB", "GMCR", "GPRE", "GCBC", "GLRE", "GRIF",
				"GRFS", "GRPN", "OMAB", "GGAL", "GSIG", "GSIT", "GSVC", "GTAT",
				"GTSI", "GTXI", "GPRC", "GBNK", "GFED", "GUID", "GIFI", "GURE",
				"GPOR", "GYRO", "HEES", "HNRG", "HALL", "HALO", "HBNK", "HMPR",
				"HBHC", "HNH", "HAFC", "HNSN", "HSOL", "HDNG", "HARL", "HLIT",
				"TINY", "HPOL", "HBIO", "HAS", "HAST", "HAUP", "HA", "HCOM",
				"HWKN", "HWBK", "HAYN", "HCSG", "HSTM", "HWAY", "HTLD", "HTLF",
				"HTWR", "HLYS", "HSII", "HELE", "HMNY", "HSIC", "HERO", "HTBK",
				"HFWA", "HBOS", "HEOP", "HCCI", "MLHR", "HSKA", "HFFC", "HIBB",
				"HTCO", "HKAC", "HKACU", "HKACW", "HIHO", "HIMX", "HIFS",
				"HSFT", "HITK", "HITT", "HMNF", "HMSY", "HOKU", "HOLI", "HOLL",
				"HOLX", "HBCP", "HOMB", "HOME", "HFBL", "HMIN", "HLSS", "AWAY",
				"HCII", "HCIIP", "HCIIW", "HMST", "HPJ", "HOFT", "HFBC",
				"HBNC", "HZNP", "HRZN", "ZINC", "HOTT", "HWCC", "HOVNP",
				"HSNI", "HUBG", "HCBK", "HSON", "HDSN", "HGSI", "HBAN",
				"HBANP", "HPCCP", "HURC", "HURN", "HTCH", "HYGS", "IDSY",
				"IACI", "IBKC", "ICAD", "IEP", "ICFI", "ICGE", "ICLR", "ICON",
				"ICUI", "IDIX", "INVE", "IDRA", "IDXX", "IROQ", "IGTE", "IRG",
				"IGOI", "IIVI", "IKAN", "IKNX", "ILMN", "ISNS", "IMMR", "ICCC",
				"IMGN", "IMMU", "IPXL", "IPSU", "IMRS", "SAAS", "INCY", "INDB",
				"IBCP", "IBCPO", "INCB", "IDSA", "INFN", "INFI", "IPCC",
				"INFA", "III", "IFON", "INFY", "IMKTA", "INWK", "INOD", "IPHS",
				"IOSP", "INOC", "ISSC", "NSIT", "ISIG", "INSM", "IIIN", "PODD",
				"IART", "INMD", "IDTI", "IESC", "ISSI", "INTC", "IPCI", "IPAR",
				"IBKR", "ININ", "IDCC", "IFSIA", "IMI", "ITMN", "INAP", "IBOC",
				"ISCA", "IGLD", "IIJI", "PTNT", "INPH", "INTX", "ISIL", "IILG",
				"IBCA", "INTT", "IVAC", "INTL", "IIN", "INTU", "ISRG", "SNAK",
				"ISBC", "IRET", "IRETP", "ITIC", "IPAS", "IPCM", "IPGP",
				"IRIX", "IRDM", "IRDMU", "IRDMW", "IRDMZ", "IRIS", "IRBT",
				"IRWD", "FCHI", "IFSM", "IFAS", "IFEU", "IFGL", "IFNA", "SOXX",
				"AXFN", "ACWX", "ACWI", "AAXJ", "EMFN", "EMMT", "EUFN", "FEFN",
				"IBB", "EMIF", "ICLN", "NUCL", "WOOD", "INDY", "ISHG", "IGOV",
				"GNMA", "AXJS", "AAIT", "EEML", "EEMA", "EMDI", "EEME", "EMEY",
				"EGRW", "EVAL", "ISIS", "ISLE", "ISRL", "ITRI", "ITRN", "IVAN",
				"XXIA", "IXYS", "JJSF", "JAX", "MAYS", "JBHT", "JCOM", "JASO",
				"JCDA", "JKHY", "JACK", "JXSB", "JAXB", "JAKK", "JMBA", "JRCC",
				"JAZZ", "JDAS", "JDSU", "JFBI", "JBLU", "JCTCF", "DATE", "JST",
				"JIVE", "JOEZ", "JBSS", "JOUT", "JSDA", "JOSB", "KALU", "KFFG",
				"KNDI", "KCLI", "KRNY", "KIPO", "KELYA", "KELYB", "KNSY",
				"KFFB", "KERX", "KEQU", "KTEC", "KTCC", "KEYN", "KFRC",
				"KBALB", "KGJI", "KINS", "KONE", "KIOR", "KIPS", "KIRK",
				"KITD", "KLAC", "KMGB", "VLCCF", "KNOL", "KCAP", "KONA",
				"KONG", "KOPN", "KOSS", "KTOS", "KSW", "KSWS", "KUTV", "KLIC",
				"KVHI", "LLEN", "FSTR", "BOOT", "LSBK", "LBAI", "LKFN", "LAKE",
				"LACO", "LRCX", "LAMR", "LANC", "LNDC", "LARK", "LSTR", "LTRX",
				"LPSB", "LSCC", "LAWS", "LAYN", "LCAV", "LCNB", "GAGA", "LBIX",
				"LEAP", "LTRE", "LCRY", "LGCY", "LMAT", "LXRX", "LHCG",
				"LBTYA", "LBTYB", "LBTYK", "LINTA", "LINTB", "LMCA", "LMCB",
				"LPHI", "LIFE", "LPNT", "LCUT", "LWAY", "LGND", "LTBR", "LPTH",
				"LIWA", "LIME", "LLNW", "LMNR", "LLGX", "LNCR", "LINC", "LECO",
				"LLTC", "LTON", "LINE", "LIOX", "LQDT", "LFUS", "LIVE", "LPSN",
				"LZEN", "JADE", "LKQ", "LMIA", "LMLP", "LNBB", "LOCM", "LNET",
				"LOGI", "LOGM", "LOJN", "LOOK", "LORL", "LABC", "LAEC", "LPLA",
				"LRAD", "LSBI", "LYTS", "LTXC", "LUFK", "LULU", "LMNX", "LMOS",
				"LUNA", "MBTF", "MTSI", "MCBC", "MFNC", "MAGS", "MGLN", "MPET",
				"MGIC", "CALL", "MAG", "MGYR", "MHLD", "MSFG", "COOL", "MMUS",
				"MMYT", "MKTAY", "MAKO", "MLVF", "MANH", "LOAN", "MNTX",
				"MTEX", "MNKD", "MANT", "MAPP", "MCHX", "MARPS", "LEDR",
				"MKTX", "MRLN", "MSHL", "MRTN", "MMLP", "MRVL", "MASI", "MASC",
				"MTRX", "MAT", "MATR", "MATW", "MFRM", "MTSN", "MXIM", "MXWL",
				"MAXY", "MFLR", "MBFI", "MCGC", "MGRC", "MDCA", "MEAD", "MEAS",
				"MCOX", "TAXI", "MDAS", "MDTH", "MDCI", "MNOV", "MDSO", "MDVN",
				"MEDW", "MTOX", "MELA", "MPEL", "MLNX", "MEMP", "MEMS", "MENT",
				"MTSL", "MELI", "MBWM", "MERC", "MBVT", "MRCY", "MRGE", "VIVO",
				"EBSB", "MMSI", "MACK", "MERU", "MSLI", "MLAB", "CASH", "MBLX",
				"MEOH", "METR", "MCBI", "MFRI", "MGEE", "MGPI", "MDH", "MCRL",
				"MCHP", "MFI", "MU", "NOIZ", "MCRS", "MSCC", "MSFT", "MSTR",
				"MVIS", "MVISW", "MPB", "MCEP", "MBRG", "MSEX", "MOFG", "SMCG",
				"MNDO", "MSPD", "MIPS", "MSON", "MSW", "MIND", "MITK", "MITL",
				"MKSI", "MODL", "MINI", "MOCO", "MPAC", "MLNK", "MOLX",
				"MOLXA", "MNTA", "MCRI", "MCBF", "MNRK", "MNRKP", "MPWR",
				"TYPE", "MNRO", "MNST", "MHGC", "MORN", "MOSY", "MPAA", "MOTR",
				"MOVE", "MSBF", "MNTG", "MTSC", "MBND", "LABL", "MFLX", "MGAM",
				"MFSF", "MWIV", "MYL", "MYRG", "MYRX", "MYGN", "NABI", "NANO",
				"NSPH", "NSSC", "NASB", "QQQX", "NAFC", "NATH", "NAUH", "NKSH",
				"FIZZ", "NCMI", "NATI", "NATL", "NPBC", "NPBCO", "NRCI",
				"NSEC", "NTSC", "NWLI", "NAII", "NATR", "BABY", "NVSL", "NMAR",
				"NMARW", "NAVR", "NBTF", "NBTB", "NCIT", "NKTR", "NEOG",
				"NEON", "NEPT", "UEPS", "NETC", "NTAP", "NTES", "NFLX", "NTGR",
				"NLST", "NTCT", "NTWK", "NTSP", "NEI", "NWK", "NBIX", "NGSX",
				"NURO", "IQNT", "NCBC", "NEBS", "NOOF", "NHTB", "HAVNP",
				"NYMT", "NBBC", "NEWL", "NLNK", "NFSB", "NEWP", "NWS", "NWSA",
				"NEWS", "NEWT", "NXST", "NEXS", "NFEC", "NGPC", "EGOV", "NICE",
				"NICK", "NIHD", "NINE", "NNBR", "NOBH", "NDSN", "NSYS", "NTK",
				"FFFD", "NOVB", "NBN", "NECB", "NTIC", "NTRS", "NFBK", "NRIM",
				"NWBI", "NWPX", "NWFL", "NVMI", "NVDQ", "NVTL", "NVAX", "NVGN",
				"NPSP", "NTLS", "NUAN", "NMRX", "PATH", "NUTR", "NTRI", "NUVA",
				"NVEC", "NVDA", "NXPI", "NXTM", "NYMX", "OIIM", "BKOR", "OVLY",
				"OBAF", "OMPI", "OBCI", "OPTT", "ORIG", "OSHC", "OCFC", "OCLR",
				"OFED", "OCLS", "OCZ", "OMEX", "OPAY", "OLCB", "OVBC", "ODFL",
				"OLBK", "OPOF", "OSBC", "OSBCP", "ZEUS", "OFLX", "OMER",
				"OABC", "OMCL", "OVTI", "ASGN", "ONNN", "OTIV", "OGXI", "ONCY",
				"ONTY", "ONFC", "ORCC", "ONSM", "ONVI", "ONXX", "OTEX", "OPEN",
				"OPXA", "OPXAW", "OPLK", "OPXT", "OBAS", "OCC", "OPTR", "OPHC",
				"ORCL", "OSUR", "ORBC", "ORBT", "ORBK", "OSH", "ORCT", "ORLY",
				"OREX", "SEED", "ORIT", "ORRF", "OFIX", "OSIS", "OSIR", "OSN",
				"OTT", "OTTR", "OUTD", "OVRL", "OSTK", "OXLC", "OXGN", "OXBT",
				"OYOG", "PFIN", "PTSI", "PFCB", "PCAR", "PACR", "PACB", "PCBC",
				"PCBK", "PEIX", "PMBC", "PPBI", "PSUN", "PCRX", "PACW", "PTIE",
				"PLMT", "PMTI", "PAAS", "PNRA", "PSOF", "PZZA", "PAMT", "PMTC",
				"PRXL", "PSTB", "PKBK", "PRKR", "PKOH", "PTNR", "PBHC", "PATK",
				"PNBK", "PATR", "PDCO", "PTEN", "PLCC", "PAYX", "PCCC", "MALL",
				"PCTI", "PDFS", "PDII", "PDLI", "PGC", "PRLS", "PEET", "PEGA",
				"PCO", "PENX", "PENN", "PFLT", "PNNT", "PWOD", "PNSN", "PEBO",
				"PEBK", "PEDH", "PEOP", "PFBX", "PBCT", "PRCP", "PPHM", "PWRD",
				"PRFT", "PTIX", "PERF", "PSEM", "PERI", "PESI", "PRGO", "PERY",
				"PVSW", "PETS", "PETD", "PETM", "PFSW", "PGTI", "PCYC", "ANTP",
				"PHII", "PHIIK", "PHMD", "PLAB", "FACE", "PICO", "PNFP",
				"PXLW", "PZZI", "PLNR", "PLXS", "PLUG", "PLBC", "PSTI", "PLXT",
				"PMCS", "PMFG", "PBSK", "PTSX", "PNTR", "PCOM", "PTEK", "PLCM",
				"POOL", "POPE", "BPOP", "BPOPM", "BPOPN", "PBIB", "PRAA",
				"PSTR", "PCH", "POWL", "POWI", "PWER", "POWR", "PSCC", "PSCD",
				"PSCE", "PSCF", "PSCH", "PSCI", "PSCM", "PSCT", "PSCU", "PRFZ",
				"PAGG", "PKOL", "PSAU", "PSTL", "PWND", "PMNA", "PNQI", "QQQ",
				"PWAV", "POZN", "PRAN", "PFBC", "PLPC", "PRXI", "PFBI", "PRWT",
				"PLFE", "PRST", "PRGX", "PCLN", "PSMT", "PBMD", "PACQ",
				"PACQU", "PACQW", "PNRG", "PRMW", "PRIM", "PNBC", "PVTB",
				"PVTBP", "PKT", "PDEX", "PGNX", "PRGS", "PFPT", "PRPH", "BIB",
				"BIS", "TQQQ", "SQQQ", "PSEC", "PWX", "PROV", "PBIP", "PSBH",
				"PSDV", "PSSI", "PMD", "PULB", "PURE", "PCYO", "PVFC", "QADA",
				"QADB", "QCCO", "QCRH", "QGEN", "QKLS", "QLIK", "QLGC", "QLTI",
				"QCOM", "QLTY", "QSII", "QBAK", "QTWW", "QSFT", "QCOR", "QUIK",
				"QDEL", "QNST", "DFZ", "RRD", "RADA", "RDCM", "ROIA", "ROIAK",
				"RSYS", "RDNT", "RDWR", "RMKR", "RMBS", "RMTR", "RAND", "RLOG",
				"GOLD", "RPTP", "RAVN", "ROLL", "RCMT", "RDA", "RLOC", "RDI",
				"RDIB", "RSOL", "RNWK", "RP", "RCON", "RECV", "RRGB", "REDF",
				"REED", "REGN", "REIS", "RELV", "MARK", "RNST", "REGI", "RCII",
				"RENT", "RGEN", "RPRX", "RPRXW", "RPRXZ", "RJET", "RBCAA",
				"FRBK", "REFR", "RIMM", "REXI", "RECN", "RGDX", "MKTG", "ROIC",
				"ROICU", "ROICW", "RTLX", "REXX", "RFIL", "RFMD", "RFMI",
				"RGCO", "RELL", "RICK", "RIGL", "RNET", "RIMG", "RITT", "RIVR",
				"RVBD", "RVSB", "ROCM", "RCKB", "RMTI", "RCKY", "RMCF", "RSTI",
				"ROIQ", "ROIQU", "ROIQW", "ROMA", "ROSG", "ROSE", "ROST",
				"ROVI", "RBPAA", "RGLD", "ROYL", "FUND", "RPXC", "RRST",
				"RTIX", "RBCN", "RTEC", "RUE", "RBNF", "RUSHA", "RUSHB",
				"SGGG", "SCOG", "SCTR", "SCLP", "RUTH", "RYAAY", "STBA",
				"SANW", "SANWW", "SANWZ", "SYBT", "SYBTP", "SABA", "SBRA",
				"SAFT", "SGNT", "SAIA", "SALM", "SLXP", "SAFM", "SNDK", "SASR",
				"SGMO", "SANM", "GCVRZ", "SNTS", "SPNS", "SAPE", "SATC",
				"SVNT", "SBAC", "SCSC", "SCBT", "SCGQ", "SMIT", "SCHN", "SCHL",
				"SCHS", "SCLN", "SGMS", "SCIL", "SQI", "SEAC", "SBCF", "STX",
				"SHIP", "SHLD", "SGEN", "SNFCA", "SEIC", "SCSS", "SLTC",
				"SIGI", "LEDS", "SMTC", "SENEA", "SENEB", "SNMX", "SQNM",
				"SREV", "SEV", "SAPX", "SVBI", "SGOC", "GAME", "SMED", "SHEN",
				"VALV", "SHLO", "BEST", "SHPGY", "SCVL", "SHBI", "SHOR",
				"SHFL", "SFLY", "SIFI", "SIEB", "BSRR", "SWIR", "SIFY", "SIGA",
				"SIGM", "SIAL", "SGMA", "SBNY", "SBNYW", "SLGN", "SILC", "SGI",
				"SIMG", "SLAB", "SIMO", "SPIL", "SSRI", "SFNC", "SLP", "SINA",
				"SBGI", "SCEI", "SCOK", "SINO", "SVA", "SIRI", "SIRO", "SKUL",
				"MOBI", "SPU", "SKBI", "SKYW", "SWKS", "ISM", "JSM", "OSM",
				"SLM", "SLMAP", "SLMBP", "SMBL", "SMT", "HEAT", "SPRO", "SWHC",
				"SMSI", "SMTX", "LNCE", "SCKT", "SODA", "SOHU", "SLRC", "SUNS",
				"SZYM", "SLTM", "SOMX", "SOMH", "SONC", "SOFO", "SONS", "SORL",
				"SDBT", "FIRE", "SOCB", "SCMF", "SCMFO", "SFST", "SMBC",
				"SONA", "SBSI", "OKSB", "OKSBP", "SPBC", "SPAN", "SBSA",
				"SGRP", "SPAR", "SPTN", "SPPI", "SPEX", "SPIR", "SAVE", "SPLK",
				"SPCHA", "SPCHB", "SPRD", "SPSC", "STRC", "SRSL", "SSNC",
				"STAA", "STMP", "STND", "SMSC", "STAN", "STLY", "SPLS", "SBLK",
				"CIGX", "SBUX", "STFC", "STBZ", "SIBC", "GASS", "STEC", "STLD",
				"SMRT", "STNR", "STEL", "STEM", "STXS", "SRCL", "STRL", "STSA",
				"SHOO", "SSFN", "STEI", "SSYS", "SDIX", "STRT", "STRS", "STRA",
				"STRM", "STB", "SCMP", "SUBK", "SUMR", "SMMF", "SSBI", "SNBC",
				"SUNH", "SNHY", "SNSS", "STKL", "SPWR", "SSH", "SMCI", "SCON",
				"SGC", "SPMD", "SUPN", "SPPR", "SPPRO", "SPPRP", "SUPX",
				"SPRT", "SURW", "SRDX", "SUSQ", "SUSS", "SBBX", "SUTR", "STRN",
				"SIVB", "SIVBO", "SWSH", "SXCI", "SCMR", "SYKE", "SYMC",
				"SYMM", "SYNC", "GEVA", "SYNL", "SYNA", "SNCR", "SURG", "SGYP",
				"SGYPU", "SGYPW", "ELOS", "SNPS", "SNTA", "SYNT", "SYMX",
				"SYNM", "SYUT", "SYPR", "TROW", "TAIT", "TTWO", "TBAC", "TLF",
				"TNGO", "TRGT", "TASR", "TATT", "TAYC", "TAYCP", "TAYD",
				"TCPC", "TSTF", "TEAR", "TECD", "TECH", "TCCO", "TTGT",
				"TECUA", "TECUB", "TGAL", "TKMR", "TSYS", "TNAV", "TSTC",
				"TTEC", "TELK", "TLAB", "WRLS", "TNGN", "TBNK", "TESO", "TSLA",
				"TESS", "TSRA", "TTEK", "TCBI", "TCBIW", "TXN", "TXRH", "THRD",
				"TFSL", "TGE", "ABCO", "ANDE", "TBBK", "BKYF", "BONT", "CG",
				"CAKE", "CHEF", "PLCE", "DSGX", "DXYN", "ENSG", "FINL", "FBMS",
				"FLIC", "TFM", "HCKT", "HAIN", "CUBA", "INTG", "KEYW", "MSG",
				"TMNG", "MDCO", "MIDD", "NDAQ", "NAVG", "PTRY", "PRSC", "SAVB",
				"SPNC", "ULTI", "WTSLA", "YORW", "NCTY", "THER", "THRX",
				"KOOL", "TST", "TCRD", "TPGI", "THOR", "THQI", "THLD", "THTI",
				"OINK", "TIBB", "TIBX", "TICC", "TIGR", "TIII", "TMWE", "TSBK",
				"TITN", "TIVO", "TISA", "TOPS", "TORM", "TRMD",
				"TRNX", "TOFC", "TWGP", "TSEM", "TWER", "CLUB", "TOWN", "TPCG",
				"TSCO", "TWMC", "TSON", "TACT", "TRNS", "TSPT", "TGA", "TTHI",
				"TXCC", "TZYM", "TZOO", "TREE", "TCBK", "TRS", "TRMB", "TRIB",
				"TRIO", "TRIP", "TQNT", "TRIT", "TSRX", "TROV", "TROVU",
				"TRLG", "TBOW", "TRST", "TRMK", "TSRI", "TTMI", "TUDO", "TUES",
				"TFCO", "TWTC", "TWIN", "USCR", "PRTS", "USEG", "GROW", "USHS",
				"USPH", "UBNT", "UFPT", "ULTA", "UCTT", "ULBI", "ULTR", "UTEK",
				"UMBF", "UMPQ", "UNAM", "UNIS", "UNB", "UDRL", "UBSH", "UNXL",
				"UBCP", "UBOH", "UBSI", "UCBA", "UCBI", "UCFC", "UBNK", "UFCS",
				"UNFI", "UNTD", "UBFO", "USBI", "USLM", "USTR", "UTHR", "UG",
				"UNTK", "UNTY", "UBPS", "UBPSU", "UBPSW", "PANL", "UEIC",
				"UFPI", "USAP", "UACL", "UVSP", "UPIP", "URRE", "URBN", "ULGX",
				"UPI", "ECOL", "USMO", "USAT", "USATP", "USATZ", "USAK",
				"UTMD", "UTIW", "UTSI", "VLNC", "VYFC", "VLYWW", "VALU",
				"VCLK", "VVTV", "VNDA", "VGIT", "VCIT", "VNQI", "VCLT", "VGLT",
				"VMBS", "VONE", "VONG", "VONV", "VTWO", "VTWG", "VTWV", "VTHR",
				"VGSH", "VCSH", "VXUS", "VDSI", "VASC", "WOOF", "VECO", "VELT",
				"VTUS", "VRA", "VSTM", "VRNM", "VRNT", "VRSN", "VRSK", "VRML",
				"VSNT", "VRTX", "VRTA", "VRTB", "VIA", "VIAB", "VSAT", "VIAS",
				"VICL", "VICR", "VIDE", "VPFG", "VBFC", "VLGEA", "VIMC",
				"VIRC", "VMED", "VCBI", "VPHM", "VSCP", "VRTS", "VRTU", "VISN",
				"VSCI", "VIST", "VPRT", "VITC", "VTSS", "VTNC", "VVUS", "VOCS",
				"VOD", "VOLC", "VLTR", "VOXX", "VSBN", "VSEC", "WACLY", "WCRX",
				"WRES", "WWVY", "WBCO", "WAFD", "WAFDW", "WASH", "WSBF",
				"WAVX", "WAYN", "WSTG", "WDFC", "WWWW", "WBMD", "WEBM", "WBSN",
				"WEBK", "WEN", "WERN", "WSBC", "WTBA", "WCBO", "WMAR", "WABC",
				"WSTL", "WDC", "WLBC", "WFD`", "WEST", "WLB", "WLBPZ", "WPRT",
				"WWAY", "WEYS", "WFM", "WILN", "WVVI", "WLDN", "WLFC", "WLFCP",
				"WIBC", "WIN", "WINA", "WWIN", "WTFC", "WTFCW", "RNIN", "WETF",
				"GULF", "EMCB", "WBKC", "WWD", "WRLD", "XWES", "WHRT", "BWOW",
				"BWOWU", "BWOWW", "WPCS", "WPPGY", "WMGI", "WSB", "WSFS",
				"WSCI", "WUHN", "WVFC", "WYNN", "XATA", "XBKS", "XNPT", "XLNX",
				"XOMA", "XRTX", "YAVY", "YHOO", "YNDX", "YONG", "YOD", "YDNT",
				"YRCW", "YTEC", "ZAGG", "ZLCS", "ZAZA", "ZBRA", "ZLTQ", "ZHNE",
				"HOGS", "Z", "ZN", "ZNWAL", "ZNWAW", "ZNWAZ", "ZION", "ZIONW",
				"ZIOP", "ZIP", "ZIPR", "ZIXI", "ZGNX", "ZOLT", "ZOOM", "ZUMZ",
				"ZIGO", "ZNGA" };
		String index = "NASDAQ";

		FileWriter fstream = new FileWriter("motions.thor");
		BufferedWriter out = new BufferedWriter(fstream);

		for (String ticker : tickers) {
			String historicalUrl = "http://www.google.com/finance/historical?q="
					+ index
					+ ":"
					+ ticker
					+ "&startdate=Jan+1%2C+2005&output=csv";

			try{
			URL url = new URL(historicalUrl);
			

			BufferedReader reader = new BufferedReader(new InputStreamReader(
					url.openStream()));

			reader.readLine(); // to skip first line
			

			String line;

			Double nextClose = 0.0;

			while ((line = reader.readLine()) != null) {
				String[] values = line.split(",");

				Double close = Double.parseDouble(values[4]);
				String date = transformDate(values[0]);
				Double difference = 0.0;

				if (nextClose > 0)
					difference = nextClose - close;

				DecimalFormat df = new DecimalFormat("##.###");
				df.format(difference / close);

				out.write(ticker + "|" + date + "|"
						+ df.format((difference / close) * 100));
				out.newLine();

				nextClose = close;
			}
			reader.close();
			}
			catch (Exception e){
				continue;
			}
		}

		out.close();

	}

	static private String transformDate(String date) throws ParseException {
		SimpleDateFormat dateParser = new SimpleDateFormat("dd-MMM-yy");
		SimpleDateFormat dateFormatter = new SimpleDateFormat("MMM dd, yyyy");
		java.util.Date parsedDate = dateParser.parse(date);
		return dateFormatter.format(parsedDate);
	}
}
